sudo: required
jobs:
  include:
   before_install:
  - "chmod +x ./mvnw"
  - stage: backend
    name: backend tests
    language: java
    jdk: oraclejdk8
    script:
    - "./mvnw clean test -B"
  - stage: backend
    name: backend test and build
    language: java
    jdk: oraclejdk8
    env:
      global:
      - CC_TEST_REPORTER_ID=af6242f9998c7e29002684f1f68c55763d6d880d5444b0971875097983da7712
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - "./mvnw clean install -B"
    after_script:
    - "./cc-test-reporter format-coverage -d -t jacoco ./backend/target/jacoco-ut/jacoco.xml"
    - "./cc-test-reporter upload-coverage -d -r af6242f9998c7e29002684f1f68c55763d6d880d5444b0971875097983da7712"
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: 64b937f4-40d8-4212-8aae-c2b7befa836f
  app: spark-backend-elte
  on:
    repo: arongyalai/spark-backend
